### ISSUE TITLE
Clusterdock does not find images for Mapr topology

### ISSUE THREAD

**Issue by israelzuniga** [clusterdock/topology_mapr#32]
After installation of Clusterdock, I tried to create a cluster with the Mapr topology but without success.
Seems that the image names are not matching the default namespace for this scenario (I tried the Hortonworks topology with full success).

This is the message displayed:

```
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: docker.io/clusterdock/clusterdock:mapr5.2.2_mep3.0.1_primary-node")
```

Also I tried, also without a solution, to modify the file `topology_mapr/start.py` with hardcoded names for the images.

Could be related to a change in the Docker hub?

---
Versions of my stack:
Clusterdock: 1.4.0
Python: 3.6
Docker: Docker version 1.13.1
Fedora Linux 27 (4.15.4-300.fc27.x86_64)

**Comment by dimaspivak** [comment]
Nope. Images need to be created by each user as we don’t have the legal right to distribute MapR binaries ourselves. The Dockerfiles should make the process simpler; just need to build them and match the naming scheme that the topology uses.

**Comment by israelzuniga** [comment]
Right! I didn’t remember the proprietary side of the Mapr distro.  I will take the path you are providing here. Thanks a lot!
